//
// This file was generated by the JPA Modeler
//
package lab5.entities;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Entity;

@Entity
public class Book extends Publication implements Serializable {

    @Basic
    private String Author;

    public Book() {

    }

    public String getAuthor() {
        return this.Author;
    }

    public void setAuthor(String Author) {
        this.Author = Author;
    }
}
