//
// This file was generated by the JPA Modeler
//
package lab5.entities;

import java.io.Serializable;
import javax.persistence.Entity;

@Entity
public class discMag extends Magazine implements Serializable {

    public discMag() {

    }
}
