//
// This file was generated by the JPA Modeler
//
package lab5.entities;

import java.io.Serializable;
import java.sql.Date;
import javax.persistence.Basic;
import javax.persistence.Entity;

@Entity
public class Magazine extends Publication implements Serializable {

    @Basic
    private Date currentIssue;

    @Basic
    private int Quantity;

    public Magazine() {

    }

    public Date getCurrentIssue() {
        return this.currentIssue;
    }

    public void setCurrentIssue(Date currentIssue) {
        this.currentIssue = currentIssue;
    }

    public int getQuantity() {
        return this.Quantity;
    }

    public void setQuantity(int Quantity) {
        this.Quantity = Quantity;
    }
}
