//
// This file was generated by the JPA Modeler
//
package lab5.entities;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;

@Entity
public class Ticket implements Serializable {

    @Basic
    private String Description;

    @Basic
    private double Price;

    @Column(nullable = false)
    @Id
    private Long id;

    @Basic
    private String Client;

    public Ticket() {

    }

    public String getDescription() {
        return this.Description;
    }

    public void setDescription(String Description) {
        this.Description = Description;
    }

    public double getPrice() {
        return this.Price;
    }

    public void setPrice(double Price) {
        this.Price = Price;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getClient() {
        return this.Client;
    }

    public void setClient(String Client) {
        this.Client = Client;
    }
}
