//
// This file was generated by the JPA Modeler
//
package test;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Embeddable;

@Embeddable
public class Address implements Serializable {

    @Basic
    private String State;

    @Basic
    private String Street;

    @Basic
    private String City;

    public Address() {

    }

    public String getState() {
        return this.State;
    }

    public void setState(String State) {
        this.State = State;
    }

    public String getStreet() {
        return this.Street;
    }

    public void setStreet(String Street) {
        this.Street = Street;
    }

    public String getCity() {
        return this.City;
    }

    public void setCity(String City) {
        this.City = City;
    }
}
