//
// This file was generated by the JPA Modeler
//
package test;

import java.io.Serializable;
import java.util.List;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;

@Entity
public class Customer extends Person implements Serializable {

    @Id
    private Long id;

    @ManyToOne(targetEntity = Employee.class)
    private Employee employee;

    @OneToMany(targetEntity = ProductOrder.class)
    private List<ProductOrder> productOrders;

    public Customer() {

    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Employee getEmployee() {
        return this.employee;
    }

    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

    public List<ProductOrder> getProductOrders() {
        return this.productOrders;
    }

    public void setProductOrders(List<ProductOrder> productOrders) {
        this.productOrders = productOrders;
    }
}
