//
// This file was generated by the JPA Modeler
//
package test;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Embedded;
import javax.persistence.Id;
import javax.persistence.MappedSuperclass;

@MappedSuperclass
public abstract class Person implements Serializable {

    @Embedded
    private Address address;

    @Id
    private Long id;

    @Basic
    private int Age;

    @Basic
    private String Name;

    public Person() {

    }

    public Address getAddress() {
        return this.address;
    }

    public void setAddress(Address address) {
        this.address = address;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getAge() {
        return this.Age;
    }

    public void setAge(int Age) {
        this.Age = Age;
    }

    public String getName() {
        return this.Name;
    }

    public void setName(String Name) {
        this.Name = Name;
    }
}
