//
// This file was generated by the JPA Modeler
//
package Test4_practical;

import Test4.ShapeInterface;
import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Entity;

@Entity
public class Square extends Shape implements Serializable, ShapeInterface {

    @Basic
    private double TheLength;

    @Basic
    private double Width;

    public Square() {
        
    } 

    public double getTheLength() {
        return this.TheLength;
    }

    public void setTheLength(double TheLength) {
        this.TheLength = TheLength;
    }

    public double getWidth() {
        return this.Width;
    }

    public void setWidth(double Width) {
        this.Width = Width;
    }

    @Override
    public double printArea() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }


}
