//
// This file was generated by the JPA Modeler
//
package Test4_practical;

import Test4.ShapeInterface;
import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Entity;

@Entity
public class Triangle extends Shape implements Serializable, ShapeInterface {

    @Basic
    private double Height;

    @Basic
    private double Base;

    public Triangle() {

    }

    public double getHeight() {
        return this.Height;
    }

    public void setHeight(double Height) {
        this.Height = Height;
    }

    public double getBase() {
        return this.Base;
    }

    public void setBase(double Base) {
        this.Base = Base;
    }

    @Override
    public double printArea() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }


}
