//
// This file was generated by the JPA Modeler
//

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.ManyToOne;

@Entity
public class cashTill implements Serializable {

    @Basic
    private Double runningTotal;

    @ManyToOne(targetEntity = SaleableItem.class)
    private SaleableItem saleableItem;

    @Id
    private Long id;

    public cashTill() {

    }

    public Double getRunningTotal() {
        return this.runningTotal;
    }

    public void setRunningTotal(Double runningTotal) {
        this.runningTotal = runningTotal;
    }

    public SaleableItem getSaleableItem() {
        return this.saleableItem;
    }

    public void setSaleableItem(SaleableItem saleableItem) {
        this.saleableItem = saleableItem;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }
}
