//
// This file was generated by the JPA Modeler
//

import java.io.Serializable;
import javax.persistence.Entity;

@Entity
public class discMag extends Book implements Serializable {

    public discMag() {

    }
}
