//
// This file was generated by the JPA Modeler
//

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Id;
import javax.persistence.MappedSuperclass;
import javax.persistence.OneToOne;

@MappedSuperclass
public abstract class Publication implements Serializable {

    @Basic
    private double Price;

    @Basic
    private int Copies;

    @OneToOne(targetEntity = SaleableItem.class)
    private SaleableItem saleableItem;

    @Basic
    private String Title;

    @Id
    private Long id;

    public Publication() {

    }

    public double getPrice() {
        return this.Price;
    }

    public void setPrice(double Price) {
        this.Price = Price;
    }

    public int getCopies() {
        return this.Copies;
    }

    public void setCopies(int Copies) {
        this.Copies = Copies;
    }

    public SaleableItem getSaleableItem() {
        return this.saleableItem;
    }

    public void setSaleableItem(SaleableItem saleableItem) {
        this.saleableItem = saleableItem;
    }

    public String getTitle() {
        return this.Title;
    }

    public void setTitle(String Title) {
        this.Title = Title;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }
}
