//
// This file was generated by the JPA Modeler
//

import java.io.Serializable;
import javax.persistence.Entity;
import javax.persistence.Id;

@Entity
public class SaleableItem implements Serializable {

    @Id
    private Long id;

    public SaleableItem() {

    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }
}
