//
// This file was generated by the JPA Modeler
//

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.OneToOne;

@Entity
public class ticket implements Serializable {

    @Basic
    private String Description;

    @Basic
    private double Price;

    @OneToOne(targetEntity = SaleableItem.class)
    private SaleableItem saleableItem;

    @Id
    private Long id;

    @Basic
    private String Client;

    public ticket() {

    }

    public String getDescription() {
        return this.Description;
    }

    public void setDescription(String Description) {
        this.Description = Description;
    }

    public double getPrice() {
        return this.Price;
    }

    public void setPrice(double Price) {
        this.Price = Price;
    }

    public SaleableItem getSaleableItem() {
        return this.saleableItem;
    }

    public void setSaleableItem(SaleableItem saleableItem) {
        this.saleableItem = saleableItem;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getClient() {
        return this.Client;
    }

    public void setClient(String Client) {
        this.Client = Client;
    }
}
